#page title
page_title                                : HS Master - Heartstone Top Decks and Meta Tier List                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1603719906                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/hsMasterIconDark.png               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : HS Master                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : ""                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : News, Top Decks and Meta Tier List for Heartstone.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Davide Ruisi                                
your_link                                 : https://github.com/davideruisi                    
your_city                                 :                                 
email_address                             : d.ruisi94@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : davide_ruisi
github_username                           : davideruisi
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : News
    description                           : Stay up to date on the Hearthstone latest news from all the best sources in the web.
    fontawesome_icon_name                 : newspaper
    
  - title                                 : Meta
    description                           : Constantly updated meta tier list, with top decks of the moment.
    fontawesome_icon_name                 : crown

  - title                                 : Card Library
    description                           : Explore the Hearthstone cards collection and show details of any card in the game.
    fontawesome_icon_name                 : book-spells



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpeg                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
